CREATE TABLE PRODUCTS(
    PRODUCT_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY, 
    MANUFACTURER VARCHAR(255),   
    PRODUCT_NAME VARCHAR(255), 
    PRICE INTEGER NOT NULL,   
    PRIMARY KEY (PRODUCT_ID)   
    );
CREATE TABLE ORDERS(
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY, 
    ORDER_ID VARCHAR(255) NOT NULL, 
    STATUS VARCHAR(255) DEFAULT 'ACCEPTED', 
    PRIMARY KEY (ORDER_ID)
    );
;
CREATE TABLE ORDER_DETAILS (     
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY, 
    ORDER_ID VARCHAR(255) NOT NULL, 
    PRODUCT_ID INTEGER NOT NULL,   
    QUANTITY INTEGER NOT NULL, 
    STATUS VARCHAR(255) DEFAULT 'ACCEPTED', 
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID)
    );   
    
CREATE TABLE ORDER_AUDITS (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY, 
    ORDER_ID VARCHAR(255) NOT NULL, 
    TOTAL_AMOUNT FLOAT NOT NULL, 
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID)
    );